---
- name: Converge
  hosts: all
  become: true
  vars:
    k3s_cluster_token: "secret"
    k3s_cluster_seed: "ubuntu-1"
    k3s_node_role: "server"
  tasks:
    - name: "Include k3s"
      ansible.builtin.include_role:
        name: "k3s"
