---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: server-1
    groups:
    - kubernetes_server
    image_arch: aarch64
    image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bullseye/latest/SHA512SUMS
    network_mode: vmnet-shared
  - name: agent-1
    groups:
    - kubernetes_agent
    image_arch: aarch64
    image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bullseye/latest/SHA512SUMS
    network_mode: vmnet-shared
  - name: agent-2
    groups:
    - kubernetes_agent
    image_arch: aarch64
    image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bullseye/latest/SHA512SUMS
    network_mode: vmnet-shared
  - name: agent-3
    groups:
    - kubernetes_agent
    image_arch: aarch64
    image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bullseye/latest/SHA512SUMS
    network_mode: vmnet-shared
provisioner:
  name: ansible
  inventory:
    host_vars:
      server-1:
        k3s_node_label:
          - topology.kubernetes.io/region=us-east-1
          - topology.kubernetes.io/zone=us-east-1a
      agent-1:
        k3s_node_label:
          - topology.kubernetes.io/region=us-east-1
          - topology.kubernetes.io/zone=us-east-1a
      agent-2:
        k3s_node_label:
          - topology.kubernetes.io/region=us-east-1
          - topology.kubernetes.io/zone=us-east-1b
      agent-3:
        k3s_node_label:
          - topology.kubernetes.io/region=us-east-1
          - topology.kubernetes.io/zone=us-east-1c
    group_vars:
      all:
        k3s_cluster_token: "secret"
        k3s_cluster_seed: "server-1"
        k3s_cluster_seed_endpoint: "192.168.64.100"
      kubernetes_server:
        k3s_node_role: server
      kubernetes_agent:
        k3s_node_role: agent
verifier:
  name: testinfra
