---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: server-1
    groups:
    - kubernetes_server
    image: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-arm64.img
    image_checksum: sha256:https://cloud-images.ubuntu.com/focal/current/SHA256SUMS
    image_arch: aarch64
    ssh_user: ubuntu
    vm_network: vmnet-shared
  - name: agent-1
    groups:
    - kubernetes_agent
    image: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-arm64.img
    image_checksum: sha256:https://cloud-images.ubuntu.com/focal/current/SHA256SUMS
    image_arch: aarch64
    ssh_user: ubuntu
    vm_network: vmnet-shared
  - name: agent-2
    groups:
    - kubernetes_agent
    image: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-arm64.img
    image_checksum: sha256:https://cloud-images.ubuntu.com/focal/current/SHA256SUMS
    image_arch: aarch64
    ssh_user: ubuntu
    vm_network: vmnet-shared
  - name: agent-3
    groups:
    - kubernetes_agent
    image: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-arm64.img
    image_checksum: sha256:https://cloud-images.ubuntu.com/focal/current/SHA256SUMS
    image_arch: aarch64
    ssh_user: ubuntu
    vm_network: vmnet-shared
provisioner:
  name: ansible
  inventory:
    host_vars:
      server-1:
        k3s_node_label:
          - topology.kubernetes.io/region=us-east-1
          - topology.kubernetes.io/zone=us-east-1a
      agent-1:
        k3s_node_label:
          - topology.kubernetes.io/region=us-east-1
          - topology.kubernetes.io/zone=us-east-1b
      agent-2:
        k3s_node_label:
          - topology.kubernetes.io/region=us-east-1
          - topology.kubernetes.io/zone=us-east-1c
      agent-3:
        k3s_node_label:
          - topology.kubernetes.io/region=us-east-1
          - topology.kubernetes.io/zone=us-east-1d
    group_vars:
      all:
        k3s_cluster_token: "secret"
        k3s_cluster_seed: "server-1"
        k3s_cluster_seed_endpoint: "192.168.64.100"
      kubernetes_server:
        k3s_node_role: server
      kubernetes_agent:
        k3s_node_role: agent
verifier:
  name: testinfra
