---
- name: Assert configuration
  ansible.builtin.assert:
    that:
      - k3s_cluster_token is defined
      - k3s_cluster_token != ""
      - k3s_cluster_seed is defined
      - k3s_cluster_seed != ""
      - k3s_node_role is defined
      - k3s_node_role in ["server", "agent"]

- name: Assert architecture
  ansible.builtin.assert:
    that:
      - ansible_facts.architecture == "x86_64" or
        ansible_facts.architecture is search("aarch64") or
        ( ansible_facts.architecture is search("arm") and ansible_facts.userspace_bits == "64" )
