---
- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true

- name: Enable IPv6 router advertisements
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "2"
    state: present
    reload: true

- name: Create k3s configuration folder
  ansible.builtin.file:
    path: "{{ k3s_service_confdir }}/config.yaml.d"
    state: directory
    mode: "0755"

- name: Create k3s state directory
  ansible.builtin.file:
    path: "{{ k3s_service_statedir }}"
    state: directory
    owner: root
    group: root
    mode: 0644
