---
- name: Register k3s cluster seed status
  ansible.builtin.stat:
    path: "{{ k3s_service_statedir }}/server/node-token"
  register: k3s_node_running

- name: Set k3s cluster seed status
  ansible.builtin.set_fact:
    k3s_node_running: "{{ k3s_node_running.stat.exists }}"

- name: Setup k3s cluster seed
  when: not k3s_node_running
  block:
    - name: Create k3s manifests directory
      ansible.builtin.file:
        path: "{{ k3s_service_statedir }}/server/manifests"
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: Disable traefik addon
      ansible.builtin.file:
        path: "{{ k3s_service_statedir }}/server/manifests/traefik.yaml.skip"
        state: touch
        owner: root
        group: root
        mode: 0644
      when: not k3s_addon_traefik_enabled

    - name: Disable local-storage addon
      ansible.builtin.file:
        path: "{{ k3s_service_statedir }}/server/manifests/local-storage.yaml.skip"
        state: touch
        owner: root
        group: root
        mode: 0644
      when: not k3s_addon_localstorage_enabled

    - name: Create kube-vip manifest for rbac
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/kube-vip/kube-vip/{{ k3s_addon_kubevip_version }}/docs/manifests/rbac.yaml"
        dest: "{{ k3s_service_statedir }}/server/manifests/kubevip-rbac.yaml"
        owner: root
        group: root
        mode: 0644
      when: k3s_addon_kubevip_enabled

    - name: Create kube-vip manifest for daemonset
      ansible.builtin.template:
        src: "kubevip.yaml.j2"
        dest: "{{ k3s_service_statedir }}/server/manifests/kubevip-daemonset.yaml"
        owner: root
        group: root
        mode: 0644
      when: k3s_addon_kubevip_enabled

    - name: Setup k3s cluster seed node
      ansible.builtin.import_tasks: 040-setup.yml

- name: Wait for k3s cluster seed endpoint to be ready
  ansible.builtin.wait_for:
    host: "{{ k3s_cluster_seed_endpoint }}"
    port: 6443
    timeout: 300
    state: started
