---
- name: Assert configuration
  ansible.builtin.import_tasks: 000-assertions.yml

- name: Prerequisite
  ansible.builtin.import_tasks: 010-prerequisite.yml

- name: Download
  ansible.builtin.import_tasks: 020-download.yml

- name: Configuration
  ansible.builtin.import_tasks: 030-configuration.yml

# - name: Create k3s configuration
#   ansible.builtin.template:
#     src: k3s.conf.j2
#     dest: /etc/rancher/k3s/config.yaml
#     owner: root
#     group: root
#     mode: 0644
#   when: ansible_hostname == hostvars[groups['kubernetes_controlplane'][0]]['ansible_hostname']

# - name: Cluster Initialization
#   ansible.builtin.import_tasks: 030-cluster-init.yml
#   # when: ansible_hostname == hostvars[groups['kubernetes_controlplane'][0]]['ansible_hostname']

# - name: Wait for node-token
#   ansible.builtin.wait_for:
#     path: /var/lib/rancher/k3s/server/node-token

# - name: Service
#   ansible.builtin.import_tasks: 040-service.yml
