---
- name: Prerequisite
  ansible.builtin.import_tasks: 010-prerequisite.yml

- name: Download
  ansible.builtin.import_tasks: 020-download.yml

- name: Initialize
  ansible.builtin.import_tasks: 030-initialize.yml

- name: Service
  ansible.builtin.import_tasks: 040-service.yml

- name: Wait for node-token
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token
