---
- name: Prerequisite
  ansible.builtin.import_tasks: 010-prerequisite.yml

- name: Download
  ansible.builtin.import_tasks: 020-download.yml

- name: Cluster Initialization
  ansible.builtin.import_tasks: 030-cluster-init.yml

- name: Wait for node-token
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Service
  ansible.builtin.import_tasks: 040-service.yml
