---
k3s_version: v1.24.14+k3s1
kubevip_version: v0.6.0

k3s_cluster_token: ""
k3s_cluster_seed: ""
k3s_cluster_seed_endpoint: 192.168.64.100

k3s_service_name: k3s
k3s_service_enabled: true

k3s_cluster_feature_gates:
- TopologyAwareHints=true

k3s_command: /usr/local/bin/k3s
k3s_command_extra_args:
  server: ""
  agent: ""
k3s_command_args:
  server: >
    {% for feature_gates in k3s_cluster_feature_gates %}
    --kube-apiserver-arg=feature-gates={{ feature_gates }}
    --kube-scheduler-arg=feature-gates={{ feature_gates }}
    --kube-controller-manager-arg=feature-gates={{ feature_gates }}
    --kube-proxy-arg=feature-gates={{ feature_gates }}
    --kubelet-arg=feature-gates={{ feature_gates}}
    {% endfor %}
    {{ k3s_command_extra_args.server }}
  agent: >
    {% for feature_gates in k3s_cluster_feature_gates %}
    --kube-proxy-arg=feature-gates={{ feature_gates }}
    --kubelet-arg=feature-gates={{ feature_gates }}
    {% endfor %}
    {{ k3s_command_extra_args.agent }}

k3s_addon_traefik_enabled: false
k3s_addon_localstorage_enabled: false
k3s_addon_kubevip_enabled: false
