---
k3s_version: v1.25.9+k3s1
kubevip_version: v0.6.0

k3s_cluster_token: ""
k3s_cluster_seed: ""
k3s_cluster_seed_endpoint: 192.168.64.100

k3s_service_name: k3s
k3s_service_enabled: true

k3s_command: /usr/local/bin/k3s
k3s_command_args: ""
